### ISSUE TITLE
Early-release TEKs are not being published since 2020-10-07

### ISSUE THREAD

**Issue by pvieito** [RadarCOVID/radar-covid-backend-dp3t-server#6]
It seems that early-release TEKs (ie. TEKs uploaded to the Radar COVID server on the same date they were generated on-device) are not being published on the `/exposed/<date>` endpoint since 2020-10-07.

You can check this issue on this summary plots (red bar graph): https://github.com/Radar-STATS/Radar-STATS/blob/master/Data/Resources/Current/RadarCOVID-Report-Summary-Plots.png

Early-release TEKs did start to be published on the Radar COVID server around 2020-09-18 (I suppose that was because  Android devices started supporting this feature): https://twitter.com/pvieito/status/1310190919224881153?s=21

**Comment by pantic79** [comment]
Hello,

we are checking this currently with Google team because actually this early-release TEK submission is only granted for debugging purposes so we are still using the API legacy mode and the only documented way to obtain the early TEK from the device is enabling the debug mode in Notification Exposure settings (and for that your Google Account must be allowlisted).

Check getTemporaryExposureKeyHistory method documentation [here](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods).

I'll keep you posted.

Thanks for your help

**Comment by pvieito** [comment]
Hi, thanks for the quick response!

> we are checking this currently with Google team because actually this early-release TEK submission is only granted for debugging purposes so we are still using the API legacy mode and the only documented way to obtain the early TEK from the device is enabling the debug mode in Notification Exposure settings (and for that your Google Account must be allowlisted).

Interesting! Maybe early-release mode was enabled by mistake for old API versions with [September 23 Google Play Services update and then fixed with the October 6 update](https://developers.google.com/android/guides/releases). It would align well with the data (column `shared_teks_uploaded_on_generation_date `): https://github.com/Radar-STATS/Radar-STATS/blob/master/Data/Resources/Current/RadarCOVID-Report-Summary-Table.csv

> I'll keep you posted.

Thanks!

**Comment by pantic79** [comment]
Hello,

confirmed by Google. This is due to an issue in a new functionality to allow early-release TEKs by application. For that, the APP owners should request to add the APP in the so called "early TEK allowlist". This allowlist is checked by the Google Play Services server and it suffered from an issue causing some APPs receiving early TEKs without being allowlisted.
As the DP-3T version we use is already ready to process early TEKs, probably we were requesting Google to allowlist the APP in the next days and hence these early TEKs will be delivered in the same day. Consider that once the request is procsessed, it can take up to ten days to be active.

I keep the issue opened in order you could check and comment once the early TEKs come back.

Thanks for your support and involvement.

**Comment by pvieito** [comment]
Great, thanks for all the info!

I will be monitoring the `shared_teks_uploaded_on_generation_date` KPI closely in the next days 😄

**Comment by pvieito** [comment]
It seems that [early-release TEKs are back](https://github.com/pvieito/Radar-STATS/blob/master/Data/Resources/Current/RadarCOVID-Report-Summary-Plots.png)! 

Thanks!
